<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{dec0af98-17e5-408d-9a84-a18f5a03faac}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bDummt : BOOL;
	rDummy : REAL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>